image: node:12.13.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - yarn_cache/

stages:
  - setup
  - test
  - build

lint:
  stage: setup
  before_script:
    - npm install
    - npm install -g eslint
  script:
    - npm run lint
